// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gateway/api/proto/gwy-project.proto

package go_micro_srv_atk_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on HelloWorldRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *HelloWorldRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Message

	return nil
}

// HelloWorldRequestValidationError is the validation error returned by
// HelloWorldRequest.Validate if the designated constraints aren't met.
type HelloWorldRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HelloWorldRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HelloWorldRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HelloWorldRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HelloWorldRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HelloWorldRequestValidationError) ErrorName() string {
	return "HelloWorldRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HelloWorldRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHelloWorldRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HelloWorldRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HelloWorldRequestValidationError{}

// Validate checks the field values on HelloWorldResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *HelloWorldResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Message

	return nil
}

// HelloWorldResponseValidationError is the validation error returned by
// HelloWorldResponse.Validate if the designated constraints aren't met.
type HelloWorldResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HelloWorldResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HelloWorldResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HelloWorldResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HelloWorldResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HelloWorldResponseValidationError) ErrorName() string {
	return "HelloWorldResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HelloWorldResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHelloWorldResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HelloWorldResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HelloWorldResponseValidationError{}
