// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/project/proto/api-project.proto

package go_micro_srv_atk_api_project

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloWorldRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" graphql:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" graphql:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" graphql:"-" bson:"-"`
}

func (m *HelloWorldRequest) Reset()         { *m = HelloWorldRequest{} }
func (m *HelloWorldRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRequest) ProtoMessage()    {}
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25b51a1117932318, []int{0}
}

func (m *HelloWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRequest.Unmarshal(m, b)
}
func (m *HelloWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRequest.Merge(m, src)
}
func (m *HelloWorldRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRequest.Size(m)
}
func (m *HelloWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRequest proto.InternalMessageInfo

func (m *HelloWorldRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The response message containing the welcome plus input message
type HelloWorldResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" graphql:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" graphql:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" graphql:"-" bson:"-"`
}

func (m *HelloWorldResponse) Reset()         { *m = HelloWorldResponse{} }
func (m *HelloWorldResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldResponse) ProtoMessage()    {}
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25b51a1117932318, []int{1}
}

func (m *HelloWorldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldResponse.Unmarshal(m, b)
}
func (m *HelloWorldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldResponse.Merge(m, src)
}
func (m *HelloWorldResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldResponse.Size(m)
}
func (m *HelloWorldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldResponse proto.InternalMessageInfo

func (m *HelloWorldResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloWorldRequest)(nil), "go.micro.srv.atk.api.project.HelloWorldRequest")
	proto.RegisterType((*HelloWorldResponse)(nil), "go.micro.srv.atk.api.project.HelloWorldResponse")
}

func init() {
	proto.RegisterFile("api/project/proto/api-project.proto", fileDescriptor_25b51a1117932318)
}

var fileDescriptor_25b51a1117932318 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0xcf, 0x4a, 0x4d, 0x2e, 0x01, 0xd1, 0x25, 0xf9, 0xfa, 0x89, 0x05, 0x99, 0xba,
	0x50, 0x11, 0x3d, 0xb0, 0x88, 0x90, 0x4c, 0x7a, 0xbe, 0x5e, 0x6e, 0x66, 0x72, 0x51, 0xbe, 0x5e,
	0x71, 0x51, 0x99, 0x5e, 0x62, 0x49, 0xb6, 0x5e, 0x62, 0x41, 0xa6, 0x1e, 0x54, 0x8d, 0x92, 0x2e,
	0x97, 0xa0, 0x47, 0x6a, 0x4e, 0x4e, 0x7e, 0x78, 0x7e, 0x51, 0x4e, 0x4a, 0x50, 0x6a, 0x61, 0x69,
	0x6a, 0x71, 0x89, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0xab, 0xa4, 0xc7, 0x25, 0x84, 0xac, 0xbc, 0xb8, 0x20, 0x3f,
	0xaf, 0x38, 0x15, 0xb7, 0x7a, 0xa3, 0x26, 0x46, 0x2e, 0x2e, 0xc7, 0x10, 0xef, 0x00, 0x88, 0x6d,
	0x42, 0x25, 0x5c, 0xbc, 0xee, 0xa9, 0x25, 0x08, 0x13, 0x84, 0xf4, 0xf5, 0xf0, 0xb9, 0x4e, 0x0f,
	0xc3, 0x69, 0x52, 0x06, 0xc4, 0x6b, 0x80, 0x38, 0x4e, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0x10, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xf3, 0x54, 0x4b, 0x2f, 0x01, 0x00, 0x00,
}
